import re
import os
import glob

raw_text = """
El laberinto de la necesidad y la quimera de la voluntad: El determinismo radical de Baruch Spinoza y la conquista de la verdadera libertad
El escándalo del pensamiento de Spinoza en el siglo XVII y su ruptura con la tradición
El 27 de julio de 1656, la próspera congregación judía de Ámsterdam emitió un decreto de excomunión (cherem) de una dureza inusitada y una severidad implacable contra un joven comerciante y estudiante del Talmud de apenas veintitrés años, llamado Baruch Spinoza.1 Las razones exactas y minuciosas de aquel edicto histórico no quedaron exhaustivamente registradas en el documento de expulsión que ha llegado hasta nuestros días, pero la historia del pensamiento filosófico y el posterior corpus literario del autor han demostrado con creces cuáles fueron las "herejías espantosas" y los actos monstruosos que motivaron una condena tan categórica.2 Para comprender la magnitud de este evento, es imperativo situarse en el contexto histórico y teológico de la época. La comunidad judía sefardí de Ámsterdam estaba compuesta en gran medida por antiguos marranos o criptojudíos portugueses y españoles que habían huido de las hogueras de la Inquisición en la Península Ibérica, buscando en los Países Bajos un refugio donde practicar su fe en libertad, aunque bajo estrictas normas de cohesión interna para no alterar la tolerancia civil de las autoridades calvinistas holandesas.3
En este frágil ecosistema de supervivencia religiosa y dogmatismo teológico, en un siglo XVII absolutamente dominado por las querellas eclesiásticas y el reciente pero avasallador paradigma filosófico instaurado por el dualismo de René Descartes, la propuesta intelectual incipiente de Spinoza supuso un seísmo de proporciones incalculables, una auténtica bomba de relojería en los cimientos de la civilización occidental.3 Al atreverse a desmantelar sistemáticamente la concepción judeocristiana de un Dios personal, providente, creador del universo a partir de la nada (creatio ex nihilo) y dotado de libre albedrío, Spinoza no solo desafiaba la ortodoxia sagrada de su propia comunidad sinagogal, sino que dinamitaba las bases metafísicas compartidas por toda la intelectualidad europea, fuesen católicos, protestantes o judíos.2 El Dios bíblico que juzga, castiga, premia, se indigna y altera el curso ordinario del universo a voluntad mediante la intervención de los milagros, fue sometido por Spinoza al más frío e implacable bisturí de la razón geométrica.5
El escándalo del spinozismo, que le valió el epíteto de "ateo" y "hereje" durante más de un siglo, radicaba fundamentalmente en su atrevimiento sin precedentes para aplicar el método geométrico y racional-deductivo no solo a la física elemental, la mecánica o la matemática, sino a las esferas supremas e intocables de la metafísica, la ontología, la ética y la teología.6 Su gran obra maestra, la Ética demostrada según el orden geométrico (Ethica ordine geometrico demonstrata), que fue redactada en latín a lo largo de muchos años y publicada póstumamente en el año 1677 por sus amigos más cercanos para evitar la censura en vida, erigió una arquitectura deductiva implacable que, partiendo de definiciones formales, axiomas evidentes por sí mismos y postulados, concluía de manera inexorable la absoluta y total necesidad de todo lo existente.6
Esta ruptura radical con la tradición escolar y teológica implicaba una profunda y dolorosa reevaluación del lugar que ocupa el ser humano en el cosmos. Hasta la irrupción de Spinoza, y de manera muy marcada y explícita en la metafísica de Descartes, el ser humano era considerado un "imperio dentro de otro imperio" (imperium in imperio), una excepción milagrosa a las leyes mecanicistas de la naturaleza gracias a la presunta posesión de un alma inmaterial, divina y una voluntad absolutamente libre capaz de iniciar cadenas causales desde cero.8 El racionalismo radical e ilustrado de Spinoza abolió este privilegio ilusorio y antropocéntrico de un plumazo.4 Al establecer un monismo sustancial inquebrantable, la Ética redujo todas las acciones de los hombres, sus pensamientos más íntimos, sus decisiones aparentemente libres y sus pasiones más turbulentas a las mismas leyes universales inmutables que rigen la caída parabólica de una piedra, el crecimiento de las plantas o las órbitas de los cuerpos celestes.10 El universo spinoziano es un tejido compacto, un bloque macizo de necesidad geométrica en el que absolutamente nada es contingente, donde el libre albedrío humano se revela como un autoengaño producto de la ignorancia estructural de nuestra mente, y donde la verdadera libertad solo puede florecer a través del esfuerzo racional, arduo y reflexivo por comprender, asumir y abrazar con alegría la inexorabilidad del todo.12
El presente artículo filosófico, destinado a la reflexión profunda, expone de manera exhaustiva, sistemática y exegética los pilares fundamentales de este determinismo metafísico revolucionario. A través de un análisis riguroso, nos adentraremos en el monismo inmanentista de la sustancia, descifraremos la inquebrantable red de la concatenación causal infinita que rige el universo, examinaremos la demolición crítica y psicológica de la voluntad cartesiana mediante sus ejemplos más ilustres, y finalmente, coronaremos el recorrido abordando las profundas y sanadoras implicaciones éticas orientadas a la conquista de la auténtica paz mental y la salvación a través del entendimiento.
La arquitectura del ser: El Monismo Sustancial y el colapso del dualismo
Para comprender la magnitud abrumadora del determinismo que postula Baruch Spinoza, es metodológicamente imperativo analizar primero la base ontológica fundacional sobre la cual se erige todo su sistema: el monismo inmanentista de las sustancias, una refutación directa y frontal de la herencia escolástica y cartesiana. René Descartes, en sus Meditaciones Metafísicas y en los Principios de la Filosofía, había postulado, en un intento de conciliar la nueva ciencia mecanicista con los dogmas de la Iglesia, la existencia de tres sustancias fundamentales que conformaban el tapiz de la realidad: la sustancia pensante (res cogitans, que comprende las mentes finitas y las almas inmateriales de los seres humanos), la sustancia extensa (res extensa, que abarca todo el universo físico, espacial, gobernable por la física y la geometría) y la sustancia infinita y perfectísima (Dios), siendo las dos primeras sustancias creadas, finitas y ontológicamente dependientes de la voluntad creadora de la última.8
Spinoza somete esta taxonomía ontológica tripartita a una crítica lógica verdaderamente devastadora en la Parte I de la Ética (De Dios). Partiendo de la definición tradicional de "sustancia" que el propio Descartes y la escolástica aceptaban —como aquello que es en sí mismo y se concibe por sí mismo; es decir, aquello cuyo concepto no necesita del concepto de ninguna otra cosa para poder formarse en la mente—, Spinoza despliega una deducción que no deja escapatoria. Argumenta que, si dos sustancias tuvieran exactamente la misma naturaleza o atributo, no podrían distinguirse lógicamente la una de la otra (serían la misma); y si tuvieran naturalezas o atributos radicalmente distintos, no tendrían nada en común, y por ende, una no podría en modo alguno ser la causa de la otra, ya que lo que no tiene nada en común no puede interactuar ni transferir causalidad.6 La conclusión lógica, implacable e ineludible de estas premisas es que es ontológicamente imposible que existan múltiples sustancias en el universo. Si la sustancia es verdaderamente independiente e incausada, solo puede existir una única sustancia, una realidad absolutamente infinita, que debe ser necesariamente causa de sí misma (causa sui) y estar dotada de una infinidad de atributos que expresan su esencia eterna. A esta única, omnipresente y omniabarcante sustancia, Spinoza la llama indistintamente Dios o la Naturaleza, acuñando la que es posiblemente la fórmula más célebre de la historia de la filosofía moderna: Deus sive Natura.12
Dimensión Ontológica Cartesiana
Dimensión Ontológica Spinoziana
Implicación Metafísica Fundamental
Sustancia Infinita (Dios trascendente)
Única Sustancia Infinita (Deus sive Natura, Dios o la Naturaleza)
Dios pierde su trascendencia. No está "fuera" del mundo observando o creando desde la nada, sino que es la totalidad misma de lo real, inmanente a todo.
Sustancia Extensa (Res Extensa, el mundo material creado)
Atributo de la Extensión (Una de las infinitas expresiones de la esencia de Dios)
La materia no es algo indigno, imperfecto o ajeno a Dios. El universo físico es una expresión directa y divina de la sustancia infinita.
Sustancia Pensante (Res Cogitans, las almas individuales)
Atributo del Pensamiento (Otra expresión esencial y paralela de la misma sustancia divina)
El alma humana pierde su estatus de sustancia inmortal e independiente. Es simplemente un modo pasajero del atributo infinito del pensamiento.

La expresión latina Deus sive Natura no es una mera fórmula retórica o una provocación poética, sino el núcleo matemático de un panteísmo racionalista o, para ser ontológicamente más precisos, un inmanentismo incondicional.7 Para Spinoza, Dios y la naturaleza son términos estrictamente equivalentes e intercambiables en la ecuación de la existencia; no existe un creador trascendente, antropomórfico y ajeno que opere desde un más allá dirigiendo el teatro del mundo.12 Todo lo que existe y puede ser concebido, desde los cúmulos de galaxias y los cuerpos celestes más masivos hasta los pensamientos más íntimos, abstractos o efímeros de la mente humana, no son sino afecciones, expresiones o "modos" de esta única sustancia divina y eterna.12
Para sistematizar esta abrumadora totalidad de lo real y evitar caer en un monismo indiferenciado y confuso, Spinoza divide conceptualmente a la Naturaleza en dos dimensiones intrínsecamente inseparables, que funcionan como dos perspectivas simultáneas de la misma realidad absoluta:
Natura naturans (La Naturaleza naturante o creadora): Es Dios en cuanto se le considera como sustancia activa, causa inmanente y libre por la sola necesidad de su ser. Representa la fuerza productora eterna, vital y originaria de la realidad, expresada a través de sus infinitos atributos (de los cuales la mente humana solo es capaz de conocer dos: el Pensamiento y la Extensión).17
Natura naturata (La Naturaleza naturada o creada): Es la inmensa totalidad de lo que se sigue lógica y necesariamente de la naturaleza de Dios. Son los efectos inmanentes, los productos pasivos de los atributos de la sustancia, que no pueden existir ni concebirse sin estar enraizados en Dios.18 Esta categoría abarca tanto los "modos infinitos" (como las leyes universales del movimiento y el reposo en la extensión, o el entendimiento absolutamente infinito en el pensamiento, así como la faz de todo el universo o facies totius universi) como los "modos finitos" (las cosas singulares: una montaña, un árbol, el cuerpo de un ser humano, o una idea específica en la mente).17
Bajo este imponente y hermético marco ontológico, el antropocentrismo imperante en la cultura renacentista y en las religiones abrahámicas pierde toda su validez, evaporándose como una quimera vanidosa.4 El ser humano deja de ser el rey de la creación. No somos sustancias independientes, ni poseemos un estatus ontológico privilegiado frente a los animales o los minerales, sino que somos simplemente modificaciones temporales, finitas y limitadas (modos) de los atributos de la Sustancia única.17 En consecuencia, Dios no ejerce una "voluntad" de manera análoga a un rey legislador o un arquitecto diseñador, pues atribuirle voluntad volitiva, intencionalidad, diseño o propósitos (lo que en filosofía se denomina causas finales o teleología) a la sustancia infinita equivaldría a admitir de manera absurda que hay algo fuera de Él que Él desea alcanzar o de lo que carece.13 Pero siendo Dios infinito, no puede carecer de nada. Dios no persigue fines; Dios actúa única y exclusivamente por la sola y ciega necesidad de la perfección de su propia esencia.19
La red inquebrantable de la causalidad: La erradicación ontológica de la contingencia
Derivada de la inmanencia radical de Dios y de su acción puramente necesaria, surge el segundo gran pilar del sistema: la necesidad incondicional, exhaustiva y geométrica de todos los fenómenos del universo. La causalidad en la filosofía de Spinoza no debe entenderse como una simple sucesión temporal de eventos observados empíricamente a través de los sentidos, sino como una derivación lógico-matemática inseparable de la realidad. Al igual que del concepto mismo de un triángulo euclidiano se sigue necesariamente, desde toda la eternidad y para toda la eternidad, que la suma de sus tres ángulos internos equivale exactamente a dos ángulos rectos, de la esencia suprema de la sustancia divina se siguen de forma ineludible, infinita y perfecta todas las cosas posibles que configuran la realidad.8
En la Parte I de la Ética ("De Dios"), Spinoza asesta el golpe definitivo contra cualquier forma de indeterminismo, formalizando la erradicación de toda contingencia y sellando cualquier posible fisura en la legalidad del cosmos a través de una serie de proposiciones cardinales, entre las que destaca con luz propia la Proposición 29.
Cita Textual: "En la naturaleza no hay nada contingente, sino que, en virtud de la necesidad de la naturaleza divina, todo está determinado a existir y obrar de cierta manera." (Ética, Parte I, Proposición 29).6
Exégesis filosófica: Esta contundente proposición constituye el acta de defunción del indeterminismo ontológico moderno. Filosóficamente, el término "contingente" se define tradicionalmente como aquello que puede ser o no ser; es decir, un evento, objeto o decisión cuya existencia, no existencia o modo de operar es igualmente posible y no está predeterminado rígidamente.6 Spinoza declara, con la frialdad de un geómetra, que semejante estatus ontológico es una pura falacia antropológica. Si nuestro intelecto admitiera que en el universo hay algo verdaderamente contingente, estaríamos postulando la existencia de un acontecimiento caprichoso que escapa a la causalidad de la naturaleza divina, rompiendo así la infinitud, la omnipotencia y la perfección de la sustancia. Para Spinoza, cada evento físico (entendido como un modo en el atributo de la Extensión) o cada idea mental (entendida como un modo en el atributo del Pensamiento) está irremisiblemente incrustado en una red infinita, densa y sin lagunas de causas singulares que lo determinan para existir y operar de un modo absolutamente específico y no de otro.6
La ilusión humana de la "contingencia", por consiguiente, no pertenece en absoluto al plano de la realidad ontológica objetiva, sino que habita exclusivamente en el plano de la epistemología y el conocimiento humano: llamamos a una cosa "contingente" o "posible" simple y llanamente porque nuestro entendimiento finito, debido a su extrema fragmentación, su limitación espacial y su cortedad temporal, ignora la colosal y abrumadora cadena total de causas ocultas que han concurrido de manera necesaria para producirla.6 La contingencia no es una propiedad de las cosas; es, en los crudos términos spinozianos, la confesión sintomática de nuestra propia ignorancia sobre el orden del universo.
Esta férrea e indisoluble determinación causal queda blindada y coronada de manera magistral apenas unas proposiciones más adelante, con una contundencia geométrica que no deja lugar a la duda teológica:
Cita Textual: "Las cosas no han podido ser producidas por Dios de ninguna otra manera y en ningún otro orden que como lo han sido." (Ética, Parte I, Proposición 33).6
Exégesis filosófica: La implicación teológica e intelectual de esta proposición número 33 es radicalmente contra-intuitiva e inaceptable para el pensamiento religioso ortodoxo de su tiempo y de siglos posteriores. Esta proposición destruye preventivamente la famosa noción del "mejor de los mundos posibles" que desarrollaría posteriormente Leibniz. Invalida desde sus cimientos la entrañable doctrina religiosa de que Dios tuvo ante su infinita inteligencia múltiples opciones de universos a crear, y que, llevado por su bondad, "eligió" libremente actualizar este mundo en concreto. Si Dios hubiera podido crear el mundo de otra manera distinta a la actual, si hubiera podido alterar el más minúsculo átomo de la creación, eso implicaría lógicamente que la naturaleza divina es mutable, arbitraria o sometida al capricho.6
Sin embargo, dado que todo fluye matemáticamente de la esencia inmutable y eterna de la Naturaleza divina (Deus sive Natura), alterar el orden del universo implicaría que Dios tendría que haber tenido una naturaleza o una esencia diferente a la que tiene, lo cual constituye el más grosero de los absurdos lógicos.20 El cosmos es un corolario absoluto de la naturaleza de la Sustancia. Es lo que es, y no podría ser un ápice distinto bajo ninguna circunstancia. El orden presente y eterno del universo es la única manifestación válida, real y necesaria del Ser en toda su majestad.6
En el nivel operativo de los "modos finitos" —esto es, las cosas singulares y particulares como los animales, los seres humanos, los fenómenos atmosféricos o las pasiones—, esta inmensa concatenación causal opera de manera regresiva ad infinitum (hacia el infinito). Un cuerpo material determinado se mueve en el espacio o se mantiene en reposo única y exclusivamente porque ha sido determinado físicamente a moverse o reposar por otro cuerpo, el cual a su vez fue impulsado ineludiblemente por un tercero, y así retrocediendo ininterrumpidamente hacia el infinito en el océano del tiempo y el espacio (Ética, Parte I, Proposición 28).6 En esta cadena horizontal infinita, nunca se llega a un "primer motor" extramundano o a una "primera causa" ajena a las leyes físicas; la causa última e inmanente de toda la red, que sostiene verticalmente cada eslabón finito, es la Sustancia infinita misma.6
La demolición psicológica cartesiana: La ilusión del libre albedrío humano
Una vez establecida la maquinaria determinista inquebrantable que rige el universo macroscópico, el siguiente paso lógico y necesario en el sistema deductivo de Spinoza es abordar la naturaleza de la mente humana, desmontando los prejuicios que la sociedad albergaba sobre ella.21 Como se ha mencionado, René Descartes había sostenido en su magna obra epistémica que el ser humano, en tanto sustancia pensante (res cogitans), está escindido internamente: por un lado, está dotado de un intelecto finito (capaz de comprender solo un número muy limitado y restringido de verdades claras y distintas) y, por otro lado, posee una voluntad libre, infinita y absoluta, semejante a la voluntad divina (una capacidad incondicionada para afirmar, negar o suspender el juicio sobre cualquier idea que se presente ante la mente).8
Para el filósofo francés, este libre albedrío inmaterial es la marca indeleble, el sello sagrado de Dios impreso en el alma humana. Además, Descartes utilizaba esta asimetría entre intelecto finito y voluntad infinita como la piedra angular de su teodicea para explicar el origen del error cognitivo y del pecado moral sin responsabilizar a Dios: nos equivocamos o pecamos porque nuestra voluntad libre se precipita arrogantemente y afirma cosas que nuestro intelecto aún no concibe con la debida claridad y distinción.8
Spinoza, aplicando la misma rigidez de su monismo, pulveriza por completo este dualismo antropológico y repudia la mera posibilidad de la existencia del libre albedrío humano, calificándolo no como un misterio insondable, sino como una mera alucinación cognitiva, un error infantil producto de nuestra constitución biológica y psicológica.11 Para Spinoza, la mente humana no es en absoluto una entidad espectral, incorpórea o sobrenatural que habita el cuerpo mecanicista como un piloto mágico gobierna su nave desde una cabina; la mente humana es algo mucho más integrado e inmanente: es simplemente la "idea" del cuerpo humano.21 Por ende, al ser un modo del atributo del Pensamiento paralelo al cuerpo físico, la mente está sometida a la misma determinación, necesidad y leyes de choque que la extensión física.17
En la Parte II de la Ética, consagrada al análisis "De la naturaleza y origen del alma" (donde Spinoza emplea intencionadamente el término latino mens o mente, en lugar de anima, para evaporar y neutralizar cualquier connotación espiritualista y religiosa tradicional 6), el filósofo emite un aserto demoledor respecto a la presunta y tan alabada facultad volitiva del hombre:
Cita Textual: "En el alma no se da ninguna voluntad absoluta o libre, sino que el alma es determinada a querer esto o aquello por una causa, que también es determinada por otra, y ésta a su vez por otra, y así hasta el infinito." (Ética, Parte II, Proposición 48).21
Exégesis filosófica: Esta célebre proposición 48 constituye el pilar psicológico fundamental del determinismo espinoziano y el golpe de gracia a la soberbia del humanismo renacentista. Spinoza argumenta lógicamente que la "Voluntad" —entendida como una facultad general abstracta, un motor inmóvil interno capaz de tomar decisiones no causadas— simplemente no existe en el tejido de la realidad; es un "universal abstracto", una entidad puramente ficticia y lingüística que los seres humanos construimos mentalmente por comodidad para agrupar nuestras decisiones, del mismo modo que inventamos el concepto general de "Blancura" para agrupar las cosas blancas.8
Lo que verdadera y empíricamente existe en la vida anímica no es la "Voluntad" con mayúscula, sino "voliciones" singulares, aisladas y determinadas: el deseo repentino de beber agua ante la sequedad de la garganta, la decisión racional de levantar un brazo, o la elección verbal de pronunciar una palabra concreta.8 Spinoza demuestra de manera incontrovertible que cada una de estas voliciones o ideas es siempre el efecto directo, necesario e inevitable de un antecedente causal, ya sea de orden psíquico interior o originado por una impresión física exterior.22 Así como una bola de billar inerte en la mesa requiere necesariamente de un impacto cinético previo y externo para desplazarse, una decisión humana en el "alma" requiere ineludiblemente una causa previa que la determine de manera unívoca a afirmar o desear algo.21
Además, para aniquilar por completo el error de Descartes, Spinoza colapsa la engañosa distinción cartesiana en una sentencia fulminante recogida en los escolios: "la voluntad y el entendimiento son lo mismo" (voluntas et intellectus unum et idem sunt).8 Toda idea concebida en la mente, por el mero hecho de ser pensada lógicamente, conlleva una afirmación o negación intrínseca a sí misma, sin requerir una facultad misteriosa y separada que otorgue su asentimiento posterior.8 Spinoza nos advierte que el pensamiento no debe reducirse a meras "pinturas mudas" o fotografías pasivas en el fondo del ojo o en el lienzo de la mente; tener una idea, como la idea de un triángulo, implica ya afirmar que sus ángulos suman 180 grados, del mismo modo que pensar en un peligro implica inmediatamente la volición de huir de él.8
Para ilustrar de la manera más pedagógica, intuitiva y a la vez contundente por qué el ser humano sostiene de manera tan obstinada y pasional la ilusión megalómana de ser el autor incausado y soberano de sus propias acciones, Spinoza desarrolló un famoso e inmortal experimento mental que no se halla en la rigidez geométrica de la Ética, sino que se encuentra detallado y expuesto de manera magistral en su extensa correspondencia personal. En la célebre y sumamente estudiada Carta 58 (fechada el 8 de octubre de 1674 y dirigida al docto G.H. Schuller, quien le había transmitido las objeciones de otros intelectuales de la época frente a su negación del libre albedrío), Spinoza despliega el elocuente ejemplo de la "piedra consciente" para desnudar sin piedad el autoengaño antropológico.
Cita Textual: "Una piedra recibe de una causa externa, que la impulsa, cierta cantidad de movimiento con la cual, después de haber cesado el impulso de la causa externa, continuará necesariamente moviéndose. [...] Conciba ahora, si lo desea, que la piedra, mientras prosigue su movimiento, piensa y sabe que ella se esfuerza, cuanto puede, por seguir moviéndose. Sin duda, esa piedra, como tan sólo es consciente de su conato y no es de ningún modo indiferente, creerá que es totalmente libre y que la causa de perseverar en el movimiento no es sino que así lo quiere. Y esta es la famosa libertad humana, que todos se jactan de tener, y que tan sólo consiste en que los hombres son conscientes de su apetito e ignorantes de las causas por las que son determinados." (Carta 58 a G.H. Schuller).10
Exégesis filosófica exhaustiva:
Este texto epistolar representa sin lugar a dudas una de las exposiciones analógicas más formidables, lúcidas y perdurables en la historia del pensamiento metafísico moderno. El análisis filosófico revela varias capas interpretativas de una profundidad inmensa:
La inercia causal y física: Al igual que la piedra inanimada de la analogía, el ser humano reacciona inevitablemente a los constantes y múltiples impactos externos e internos (condicionamientos biológicos, pulsiones fisiológicas, presiones sociales, traumas históricos y afectos presentes) mediante la ley inquebrantable del movimiento físico o el afecto psíquico. Somos literalmente empujados y arrastrados por fuerzas determinantes que preceden a nuestra existencia mucho antes de que podamos siquiera formular conscientemente cualquier intención.11
El principio vital del Conatus: Spinoza menciona explícitamente en la carta que la piedra en movimiento es consciente de su tenaz esfuerzo por perseverar en el ser. Este esfuerzo ontológico no es un concepto menor; es la piedra angular de la antropología spinoziana, el célebre conatus.11 Todo ente que existe en el universo tiende espontáneamente a preservar su existencia y a aumentar su potencia de obrar contra todo lo que amenace con destruirlo. En el ser humano, cuando este conatus se refiere simultáneamente a la mente y al cuerpo, y somos conscientes de él, se manifiesta psicológicamente como deseo (cupiditas).21 Este irrefrenable impulso vital y deseante constituye la esencia misma, el motor interno y la identidad de la mente humana.21
La génesis de la ilusión cognitiva: La trampa psicológica del libre albedrío, por consiguiente, no es un dictado de la intuición divina, sino un lamentable subproducto del propio aparato cognitivo humano. La luz de nuestra conciencia ilumina perfectamente los resultados del proceso (es decir, nuestros deseos ardientes, nuestras inclinaciones y apetitos presentes), pero mantiene en la más absoluta, ciega y opaca oscuridad las complejas y milenarias cadenas causales que los engendraron en primera instancia.11 Experimentamos el deseo de venganza, de amor o de sed de manera innegablemente patente e inmediata en la conciencia, pero el origen, la trama mecanicista que encendió ese deseo, permanece fuera de nuestro campo de visión.11 Creemos ser los autores soberanos de la decisión simplemente porque ignoramos a los verdaderos autores, que son la infinita red de determinaciones cósmicas.
Como añade el propio Spinoza de forma irónica y clarificadora en la misma Carta 58 a Schuller, a causa de esta ceguera causal inherente a nuestra biología, "el niño cree apetecer libremente la leche, el chico irritado querer la venganza, y el tímido la fuga".11 En todos estos casos cotidianos, las pasiones y los instintos gobiernan el intelecto con puño de hierro, mientras que la mente, sumida en el engaño, teje justificaciones a posteriori para creer que ha elegido libremente su propio determinismo. La falsa libertad cartesiana, por tanto, no es más que ignorancia de las causas cristalizada y erigida en una gigantesca vanidad ontológica.11
La verdadera libertad spinoziana: La emancipación a través del conocimiento de la necesidad
Tras llevar a cabo la sistemática y metódica demolición de la libertad concebida vulgarmente como un libre albedrío incausado o una voluntad desvinculada, el imponente sistema deductivo de Spinoza corre el aparente riesgo de desembocar en un fatalismo oscuro, paralizante y lúgubre, propio de una tragedia griega, en el cual el sujeto humano queda trágicamente reducido a una simple marioneta pasiva arrojada a los vientos irracionales del destino, desprovista de toda ética o posibilidad de mejora. Sin embargo, es precisamente aquí, en el núcleo candente de este mecanicismo riguroso y determinismo absoluto, donde Spinoza, con un giro intelectual sublime, erige de las cenizas de la vieja teología su propio, luminoso y revolucionario concepto de la "verdadera libertad".3
La genialidad de Spinoza reside en una redefinición conceptual. Si la voluntad incausada es un oxímoron lógico absurdo y una absoluta imposibilidad material (un efecto sin causa) 30, entonces el antónimo filosófico legítimo de la palabra "libertad" nunca ha sido, ni puede ser, la "necesidad". En la geometría existencial de Spinoza, libertad y necesidad no son en absoluto fuerzas antagónicas y excluyentes; por el contrario, en el nivel más alto del ser, se presuponen y se funden mutuamente en un abrazo inextricable.29 El verdadero y único antónimo de la libertad humana es la coacción, la imposición ajena o la servidumbre pasional.10
Según las definiciones que vertebran la Parte I de la Ética, se dice legítimamente que una cosa es "libre" cuando existe única y exclusivamente por la sola necesidad inmanente de su propia naturaleza y es determinada a obrar por sí misma, sin mediación de fuerzas hostiles externas. Siguiendo este altísimo estándar ontológico, en un sentido absoluto y ontológico puro, solo Dios (la única sustancia infinita) es perfecta y absolutamente libre, ya que no existe nada fuera de Él y, por lo tanto, ninguna fuerza externa, obstáculo o causa extraña puede constreñirlo, obligarlo o desviarlo de su ser; Dios actúa eternamente y únicamente en virtud de las inmutables leyes necesarias de su propia perfección y plenitud inmanentes.11
No obstante, el ser humano, en su precaria condición de modo finito sometido ineludiblemente, desde que nace hasta que muere, a los furiosos embates, presiones y estímulos del mundo exterior de la extensión, puede aspirar, mediante un arduo trabajo interior, a alcanzar grados paulatinos y crecientes de esta misma libertad divina. Esta grandiosa aspiración de emancipación se vehicula única y exclusivamente a través de la vía epistémica, es decir, mediante la conquista racional y el ejercicio de la inteligencia.4 Somos "esclavos" (siervos miserables de nuestras fluctuantes pasiones, a merced del miedo y la esperanza) cuando nuestra conducta es dictada ciegamente por causas externas que nos arrastran, mediante el conocimiento confuso, supersticioso o lo que Spinoza llama el conocimiento de la "imaginación".31 Por el contrario, somos verdaderamente "libres" en la medida en que somos nosotros mismos la "causa adecuada" de nuestras acciones en el mundo; es decir, cuando nuestros actos y decisiones emanan lógicamente de una comprensión racional, activa y profunda de las leyes ineludibles de la Naturaleza y del conocimiento exhaustivo de nuestra propia esencia como seres finitos.13
El puente geométrico, psicológico y terapéutico que permite a la mente transitar penosamente desde las turbias ciénagas de la esclavitud pasional hacia la claridad soberana de la libertad racional se cristaliza magistralmente en los formidables axiomas y demostraciones de la Parte V de la Ética ("Del poder del entendimiento o de la libertad humana"). Allí, Spinoza enuncia una de las máximas más profundamente psicológicas de toda la modernidad:
Cita Textual: "Un afecto que es una pasión deja de ser pasión tan pronto como nos formamos de él una idea clara y distinta." (Ética, Parte V, Proposición 3).13
Exégesis filosófica exhaustiva: El impacto psicoterapéutico, curativo e intelectual de esta proposición es inmenso y se ha considerado un claro precursor histórico del psicoanálisis y de las terapias cognitivo-conductuales contemporáneas. Para comprenderla, debemos acudir a sus definiciones técnicas: una "pasión" (del latín passio, padecer o sufrir) es, por definición en el rígido vocabulario del spinozismo, un estado oscuro y pasivo del alma.21 Una pasión ocurre ineludiblemente cuando el individuo sufre los embates y los efectos de causas exteriores adversas que no comprende en absoluto, lo cual genera en su interior lo que Spinoza denomina "ideas inadecuadas" o mutiladas de la realidad.21 Emociones devastadoras como la tristeza depresiva, el odio visceral, la envidia corrosiva o el terror paralizante ante el futuro son categorizados estrictamente como afectos pasivos, precisamente porque bloquean la actividad de la mente y reducen violentamente nuestro conatus o potencia ontológica de obrar en el mundo.28
Sin embargo, frente a esta tempestad pasional, el intelecto humano posee una capacidad terapéutica luminosa e inherente a su naturaleza reflexiva: puede tomar distancia crítica de su propio afecto confuso. Cuando el sujeto racional examina con frialdad analítica su propia ira frente a un enemigo o su tristeza ante una pérdida, encendiendo la luz del entendimiento para analizar minuciosamente las redes causales, necesarias e impersonales que han desencadenado dicho estado mental en su cuerpo 28, ocurre una maravillosa transmutación ontológica en el interior de la mente. La turbia "idea confusa" de la aflicción se transmuta milagrosamente en una "idea clara y distinta" sobre el orden de las leyes de la naturaleza y nuestra propia vulnerabilidad.13 Al comprender racionalmente, sin distorsiones, el porqué profundo, estructural y necesario de nuestro propio padecimiento, el padecimiento mismo pierde ipso facto su cualidad de pasión dolorosa que nos controla, y se convierte en una pura e iluminadora acción geométrica del pensamiento.13
Dejamos de ser troncos arrastrados ciegamente río abajo por el ímpetu incontrolable del evento exterior, para elevar nuestra mente a una serena y majestuosa comprensión activa de su inquebrantable necesidad causal. La libertad espinoziana no radica, por lo tanto, en el estúpido y soberbio intento de alterar mágicamente las leyes inmutables del universo cósmico para que se acomoden egoístamente a nuestro efímero deseo antropocéntrico —una pretensión tan infantil, absurda y fútil como suplicar de rodillas que la suma de los ángulos de un triángulo equivalga de repente a tres ángulos rectos para complacernos—, sino en armonizar rítmicamente nuestro propio entendimiento humano con el flujo inexorable del Deus sive Natura.5 Libertad, en la magna, exigente y racional concepción de Spinoza, es simple y llanamente el conocimiento lúcido, afirmativo y alegre de la necesidad absoluta.12
Conclusión: Las implicaciones éticas radicales, la conquista de la paz mental y la superación del remordimiento
La imperecedera grandiosidad de la Ética demostrada según el orden geométrico de Baruch Spinoza no reside únicamente en su gélido rigor lógico o en la belleza matemática de su deducción metafísica. Su verdadera grandeza radica en que esta arquitectura especulativa nunca se pierde ni se diluye en un intelectualismo estéril de torre de marfil; toda la intrincada estructura de axiomas, infinitos corolarios y largos escolios converge irrevocablemente hacia un propósito existencial supremo y pragmático: la instauración de la ética como forma vital de sanación, la superación definitiva del sufrimiento humano originado en la ignorancia, y la obtención racional de la serenidad inalterable o beatitud.16 La asunción profunda, radical e interiorizada de que todo está determinado en el universo no engendra, en contra de las críticas teológicas de la época, una resignación lúgubre, abyecta o pesimista frente a la existencia, sino que es el umbral para alcanzar una paz mental absoluta e inquebrantable.33
El razonamiento moral espinoziano es implacable: si todo lo que ocurre a nuestro alrededor fluye y cristaliza inevitable y eternamente a partir de la suprema necesidad de Dios 20, el error primordial del ser humano en su vida afectiva es vivir presa de la indignación, el odio y la culpa culposa. Todos estos oscuros sentimientos humanos están alimentados por la misma falsa premisa ontológica: la creencia ilusoria y arrogante de que "las cosas pudieron haber sido de otro modo" y de que el libre albedrío pudo haber elegido una alternativa más noble. El veneno del odio visceral hacia el prójimo que nos agravia se disipa de inmediato cuando la mente comprende, con fría y compasiva lucidez racional, que el individuo despreciable, el criminal o el malvado han actuado determinados y coaccionados desde la cuna por gigantescas cadenas causales biológicas, pasiones oscuras, carencias psicológicas o determinantes sociales que le eran absolutamente insoslayables. Es filosóficamente tan irracional y estúpido odiar a la persona que, presa de su ignorancia, nos ofende, como lo sería indignarnos y odiar a ciegas a una nube que, por necesidad atmosférica, nos empapa de lluvia, o enfurecernos con una piedra que tropieza en nuestro camino.30 Esta grandiosa comprensión metafísica actúa como un bálsamo que neutraliza la raíz misma de la ira, la hostilidad social y el resentimiento inútil que destruyen el conatus del individuo.33
Asimismo, y de manera aún más escandalosa para la religión cristiana dominante en el siglo XVII, Spinoza ataca con una ferocidad inusitada las afecciones autodestructivas dirigidas hacia uno mismo, particularmente la culpa y la piedad ciega, las cuales eran ensalzadas hipócritamente como las más grandes virtudes morales y pilares de la salvación por los teólogos de la época.
Cita Textual: "El arrepentimiento no es virtud, es decir, que no surge de la razón; sino que quien se arrepiente de lo hecho es doblemente miserable o impotente." (Ética, Parte IV, Proposición 54).30
Exégesis filosófica exhaustiva: Para la ortodoxia moral, el arrepentimiento doloroso y la culpa torturante son indicios inequívocos de una conciencia recta y de un alma que busca a Dios.35 Para el naturalismo inmanente, determinista y vitalista de Spinoza, por el contrario, son gravísimas enfermedades del alma, patologías emocionales alimentadas por un pernicioso error metafísico. Quien siente un amargo remordimiento se atormenta internamente bajo la nociva ilusión de que podría haber actuado de forma distinta a como de hecho lo hizo, ignorando por completo la cadena de necesidad inmanente que provocó el acto, y debilitando inútilmente su potencia vital actual en flagelaciones estériles.30
Spinoza asevera, desde la cúspide de su razón práctica, que quien experimenta arrepentimiento es "doblemente miserable e impotente" porque, en primer lugar, demostró su debilidad al sucumbir ciegamente ante un mal (al cometer el acto negativo determinado por una causa exterior adversa o un afecto sumamente confuso que nubló su juicio) y, en segundo lugar, en lugar de enmendar el daño mediante el progreso activo de su racionalidad presente, se regodea pasivamente en un afecto doloroso y deprimente (el remordimiento mismo) que añade un nuevo sufrimiento a la miseria inicial, mermando severamente su sagrada capacidad de obrar, pensar y alegrarse en el momento presente.35
En otra de las contundentes proposiciones asociadas (Proposición 55 de la Parte IV), el autor nos recuerda que "la máxima soberbia o la máxima abyección es la máxima ignorancia de sí mismo".35 La verdadera sabiduría ética no se detiene a derramar lágrimas infantiles ni a pedir perdones mágicos sobre los inquebrantables engranajes necesarios del cosmos que ya han girado; por el contrario, la luz de la razón nos enseña a comprender matemáticamente nuestro propio error, a examinar la concatenación que nos llevó a fallar, y a avanzar enfocándonos de manera pragmática y activa en elegir el menor de los males y el mayor de los bienes viables en el futuro para asegurar nuestra firme autoconservación y apuntalar la prosperidad y el amor en la comunidad de los hombres libres.36
Finalmente, al erradicar por completo del horizonte humano la vanidosa ilusión antropocéntrica del libre albedrío, al destruir la culpa vacua que envenena la mente, y al disolver las fantasías teleológicas de un Dios providente que premia y castiga en una vida ultraterrena, el sujeto spinoziano se eleva victorioso hacia lo que el filósofo denomina el "tercer género de conocimiento": la intuición racional suprema (scientia intuitiva). Desde esta inmensa e incorruptible cumbre epistémica, la mente humana abandona la estrechez de miras de la temporalidad ansiosa y contempla la infinita, gloriosa y sagrada concatenación geométrica de las cosas y la inmanencia de Dios no ya bajo la angustia del tiempo fugaz, sino "bajo el aspecto de la eternidad" (sub specie aeternitatis).4
Esta contemplación extática, libre de las cadenas del miedo y de la inútil esperanza, desencadena el último y más alto peldaño del sistema moral de Spinoza: el Amor intellectualis Dei (el amor intelectual a Dios).16 A diferencia diametral del amor pasional humano, contingente, mezquino, fluctuante y siempre dependiente de objetos finitos que nacen y perecen en el dolor, este amor racional a la Naturaleza es el conocimiento absolutamente desinteresado, imperturbable y claro de la infinita conexión cósmica.16 Al comprender profunda e integralmente cómo está estructurado el universo necesario y al verse a sí mismo como una minúscula pero esencial parte indisoluble del Todo 37, la mente participa activamente de esa misma eternidad. A través del prisma puro del orden geométrico, el ser humano se purga por fin de toda la angustia terrorífica de lo imprevisible. Baruch Spinoza, al despojar a la humanidad del pedestal artificial, infantil e infundado de una falsa voluntad, no humilló en absoluto la genuina dignidad del hombre; muy por el contrario, le otorgó el anclaje existencial más firme y sublime posible: la disolución alegre de nuestro sufrimiento individual transitorio en la perfección gozosa, serena y eterna del Todo inmanente. La mayor virtud concebible de la mente humana, como sentenció con insuperable grandeza el sabio neerlandés que fue excomulgado por su atrevimiento, se realiza plena y únicamente al alcanzar a comprender a Dios, que no es otra cosa y no puede ser otra cosa que conocer, amar y abrazar el rostro inmutable, infinito y matemáticamente perfecto de la propia Naturaleza.
"""

# Clean up citations replacing punctuation followed by digits then space with punctuation and space, or at end.
c = re.sub(r'([\.\)\"])\d+([ \n\.\,]|$)', r"\1\2", raw_text)

# Clean specific separated footnotes
c = c.replace("Todo 37,", "Todo,")
c = c.replace("cuerpo 28,", "cuerpo,")
c = c.replace("causa) 30,", "causa),")
c = c.replace("Dios 20,", "Dios,")
c = c.replace("Proposición 28).6", "Proposición 28).")
c = c.replace("tradicional 6),", "tradicional),")

lines = [line.strip() for line in c.split("\n") if line.strip()]

title = lines[0]
subtitle = lines[1]
body_lines = lines[2:]

main_content_html = []
in_table = False
for line in body_lines:
    if line.startswith("Dimensión Ontológica Cartesiana"):
        continue  # skip the table start marker
    
    if "Cita Textual:" in line:
        quote = line.replace("Cita Textual: ", "")
        main_content_html.append(f"""
        <blockquote style="border-left: 3px solid var(--gold); padding-left: 1.5rem; margin: 3rem 0; font-family: 'Cinzel', serif; font-size: 1.25rem; color: var(--gold); font-style: italic; line-height: 1.8;">
            {quote}
        </blockquote>
        """)
    elif "Exégesis filosófica" in line:
        main_content_html.append(f"""<p><strong style="color: var(--gold); font-family: 'Cinzel', serif; letter-spacing: 1px;">Exégesis filosófica:</strong> {line.replace("Exégesis filosófica exhaustiva: ", "").replace("Exégesis filosófica: ", "")}</p>""")
    elif line == "La arquitectura del ser: El Monismo Sustancial y el colapso del dualismo" or line == "La red inquebrantable de la causalidad: La erradicación ontológica de la contingencia" or line == "La demolición psicológica cartesiana: La ilusión del libre albedrío humano" or line == "La verdadera libertad spinoziana: La emancipación a través del conocimiento de la necesidad" or line == "Conclusión: Las implicaciones éticas radicales, la conquista de la paz mental y la superación del remordimiento":
        main_content_html.append(f"<h2>{line}</h2>")
    elif 'La expresión latina Deus sive Natura no es una mera fórmula retórica' in line:
        # Table insertion right before this line
        table_html = """
        <div class="elegant-text-container" style="max-width: 900px; margin: 4rem auto; overflow-x: auto;">
            <table style="width: 100%; border-collapse: collapse; text-align: left; font-size: 1.05rem; color: var(--text-muted); line-height: 1.6;">
                <thead>
                    <tr style="border-bottom: 2px solid var(--gold); color: var(--gold); text-transform: uppercase; letter-spacing: 1px;">
                        <th style="padding: 1.5rem 1rem;">Dimensión Ontológica Cartesiana</th>
                        <th style="padding: 1.5rem 1rem;">Dimensión Ontológica Spinoziana</th>
                        <th style="padding: 1.5rem 1rem;">Implicación Metafísica Fundamental</th>
                    </tr>
                </thead>
                <tbody>
                    <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
                        <td style="padding: 1.5rem 1rem;">Sustancia Infinita (Dios trascendente)</td>
                        <td style="padding: 1.5rem 1rem; color: var(--text-pure); font-weight: 500;">Única Sustancia Infinita (Deus sive Natura, Dios o la Naturaleza)</td>
                        <td style="padding: 1.5rem 1rem;">Dios pierde su trascendencia. No está "fuera" del mundo observando o creando desde la nada, sino que es la totalidad misma de lo real, inmanente a todo.</td>
                    </tr>
                    <tr style="border-bottom: 1px solid rgba(255,255,255,0.05);">
                        <td style="padding: 1.5rem 1rem;">Sustancia Extensa (Res Extensa, el mundo material creado)</td>
                        <td style="padding: 1.5rem 1rem; color: var(--text-pure); font-weight: 500;">Atributo de la Extensión (Una de las infinitas expresiones de la esencia de Dios)</td>
                        <td style="padding: 1.5rem 1rem;">La materia no es algo indigno, imperfecto o ajeno a Dios. El universo físico es una expresión directa y divina de la sustancia infinita.</td>
                    </tr>
                    <tr>
                        <td style="padding: 1.5rem 1rem;">Sustancia Pensante (Res Cogitans, las almas individuales)</td>
                        <td style="padding: 1.5rem 1rem; color: var(--text-pure); font-weight: 500;">Atributo del Pensamiento (Otra expresión esencial y paralela de la misma sustancia divina)</td>
                        <td style="padding: 1.5rem 1rem;">El alma humana pierde su estatus de sustancia inmortal e independiente. Es simplemente un modo pasajero del atributo infinito del pensamiento.</td>
                    </tr>
                </tbody>
            </table>
        </div>
        """
        main_content_html.append(table_html)
        main_content_html.append(f"<p>{line}</p>")
    elif line == "La inercia causal y física:" or line.startswith("Dimensión Ontológica") or line.startswith("Implicación Metafísica") or "Sustancia Infinita (" in line or "Única Sustancia Infinita" in line or "Dios pierde su" in line or "Sustancia Extensa (" in line or "Atributo de la " in line or "La materia no es algo " in line or "Sustancia Pensante (" in line or "Atributo del Pensamiento" in line or "El alma humana pierde su" in line:
        continue # skip remaining parts of table
    else:
        # Check if it looks like a bullet point (used in exegesis parts sometimes)
        if ":" in line and not line.endswith(":") and len(line.split(":")[0].split()) < 6:
            parts = line.split(":", 1)
            main_content_html.append(f"""<p><strong style="color: var(--gold);">{parts[0]}:</strong>{parts[1]}</p>""")
        else:
            main_content_html.append(f"<p>{line}</p>")

html_injections = "\n            ".join(main_content_html)

filepath = "/Users/eduhual/Documents/COPLESTON_INSTITUTE/art_filosofia_1.html"
with open(filepath, "r", encoding="utf-8") as f:
    original = f.read()

# Replace <title>
original = re.sub(r"<title>.*?</title>", f"<title>Filosofía | Instituto Copleston</title>", original)

# Replace main title
original = re.sub(r"<h1 class=\"article-main-title\">.*?</h1>", f"<h1 class=\"article-main-title\">{title}</h1>", original, flags=re.DOTALL)

# Replace reading time and date
original = re.sub(r"Octubre 12, 2026", "Marzo 15, 2026", original)
original = re.sub(r"Lectura de 8 min", "Lectura de 15 min", original)

start_idx = original.find("<section class=\"article-body\">") + len("<section class=\"article-body\">")
end_idx = original.find("<div style=\"text-align: center; margin-top: 6rem;\">", start_idx)

new_content = original[:start_idx] + "\n            " + f"<h2>{subtitle}</h2>" + "\n            " + html_injections + "\n            " + original[end_idx:]

title_short = "El determinismo radical de Baruch Spinoza"
desc_short = "La conquista de la verdadera libertad y la demolición de la voluntad cartesiana (Marzo 15)"

for file in glob.glob("/Users/eduhual/Documents/COPLESTON_INSTITUTE/*.html"):
    with open(file, "r", encoding="utf-8") as ff:
        cc = ff.read()
    cc = re.sub(r"<h3>El Estoicismo en la Sala de Juntas</h3>", f"<h3>{title_short}</h3>", cc)
    cc = re.sub(r"<p class=\"elegant-text\">Cómo los principios de Marco Aurelio redefinen el liderazgo moderno \(Oct\. 12\)\.</p>", f"<p class=\"elegant-text\">{desc_short}</p>", cc)
    with open(file, "w", encoding="utf-8") as ff:
        ff.write(cc)

with open(filepath, "w", encoding="utf-8") as f:
    f.write(new_content)

print("Article parsed and updated successfully.")
